### ISSUE TITLE
Стайл

### ISSUE THREAD

**Issue by andrewmozolev** [OlegFilth/bonfire#4]
https://github.com/OlegFilth/bonfire/blob/6122b9a9a092e88249b206c6243dc4c6bfe3076b/sass/components/_navigation.scss#L1-L7

Очень странно выглядит & {...}
Можно просто написать
``` 
.navigation { 
   padding: 2rem 0; 
   border-top: 1px solid rgba($gray, .5); 
   border-bottom: 1px solid rgba($gray, .5); 
 }

**Comment by OlegFilth** [comment]
помутнение..)
